import Header from '@/src/components/Home/Header';
import { cn } from '@/src/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, ' bg-themeBlack text-textWhite')}>
        <main>
          <section className="z-10 absolute w-[100%]">
            <Header />
          </section>

          {children}
        </main>
      </body>
    </html>
  );
}
